name: Build and Sign CrossSum App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Code Checkout 
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller crossSum.py `
            --name crossSum `
            --windowed `
            --onefile `
            --noupx `
            --icon=assets/icon/icon.ico `
            --add-data "assets/icon/icon.ico;assets/icon"
        shell: powershell

      - name: Create temporary certificate (self-signed)
        run: |
          New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=CrossSum Dev" -CertStoreLocation "Cert:\CurrentUser\My"
        shell: powershell

      - name: Locate signtool.exe
        id: find-signtool
        shell: powershell
        run: |
          $path = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe `
            | Where-Object { $_.FullName -match 'x64\\signtool.exe$' } `
            | Select-Object -First 1 -ExpandProperty FullName
          "signtool=$path" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Sign the executable
        run: |
          $cert = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -eq "CN=CrossSum Dev" }
          $certPath = "$env:TEMP\cert.cer"
          Export-Certificate -Cert $cert -FilePath $certPath

          $signtool = "${{ steps.find-signtool.outputs.signtool }}"
          & "$signtool" sign /n "CrossSum Dev" /fd sha256 /tr http://timestamp.digicert.com /td sha256 "dist/crossSum.exe"
        shell: powershell

      - name: Upload signed executable
        uses: actions/upload-artifact@v4
        with:
          name: crosssum-windows
          path: dist/crossSum.exe
