name: Build CrossSum Windows Installer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🔧 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv\Scripts\activate
          pip install -r dev-requirements.txt

      - name: ⚙️ Compile Executable with PyInstaller
        run: |
          venv\Scripts\activate
          pyinstaller crossSum.py `
            --noconsole `
            --add-data "assets/icon/icon.ico;assets/icon" `
            --distpath dist `
            --workpath build `
            --specpath . `
            --name crossSum `

      - name: 🔐 Create self-signed certificate
        run: |
          New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=CrossSum Dev" -CertStoreLocation "Cert:\CurrentUser\My"
        shell: powershell

      - name: 📍 Locate signtool.exe
        id: find-signtool
        run: |
          $path = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe `
            | Where-Object { $_.FullName -match 'x64\\signtool.exe$' } `
            | Select-Object -First 1 -ExpandProperty FullName
          "signtool=$path" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        shell: powershell

      - name: ✍️ Sign executable
        run: |
          $cert = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -eq "CN=CrossSum Dev" }
          $certPath = "$env:TEMP\cert.cer"
          Export-Certificate -Cert $cert -FilePath $certPath

          $signtool = "${{ steps.find-signtool.outputs.signtool }}"
          & "$signtool" sign /n "CrossSum Dev" /fd sha256 /tr http://timestamp.digicert.com /td sha256 "dist/crossSum/crossSum.exe"
        shell: powershell

      - name: 📦 Download & Install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
          Start-Process .\is.exe -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
        shell: powershell

      - name: 🛠️ Build Setup Wizard (Installer)
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: powershell

      - name: 📤 Upload final installer
        uses: actions/upload-artifact@v4
        with:
          name: crosssum-windows-installer
          path: Output/CrossSumInstaller.exe
