name: Build and Sign CrossSum App

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller crossSum.py `
            --noconsole `
            --add-data "assets/icon/icon.ico;assets/icon" `
            --distpath dist `
            --workpath build `
            --specpath . `
            --name crossSum
        shell: powershell

      - name: Create temporary certificate (self-signed)
        run: |
          New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=CrossSum Dev" -CertStoreLocation "Cert:\CurrentUser\My"
        shell: powershell

      - name: Locate signtool.exe
        id: find-signtool
        shell: powershell
        run: |
          $path = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe |
            Where-Object { $_.FullName -match 'x64\\signtool.exe$' } |
            Select-Object -First 1 -ExpandProperty FullName
          "signtool=$path" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Sign the executable
        run: |
          $cert = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -eq "CN=CrossSum Dev" }
          $signtool = "${{ steps.find-signtool.outputs.signtool }}"
          & "$signtool" sign /n "CrossSum Dev" /fd sha256 /tr http://timestamp.digicert.com /td sha256 "dist/crossSum/crossSum.exe"
        shell: powershell

      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
          Start-Process -FilePath ".\is.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-" -Wait
        shell: powershell

      - name: Build Setup Wizard with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\Compil32.exe" "${{ github.workspace }}\installer.iss"
        shell: powershell

      - name: Confirm Setup Wizard was created
        run: |
          if (!(Test-Path "Output/CrossSum_Setup.exe")) {
            Write-Error "Setup file not found!"
            exit 1
          }
        shell: powershell

      - name: Upload Setup Wizard
        uses: actions/upload-artifact@v4
        with:
          name: CrossSum_Setup
          path: Output/CrossSum_Setup.exe
